### ISSUE TITLE
Update pronouns to be more inclusive

### ISSUE THREAD

**Issue by melanierichards** [bevacqua/hubby#6]
Hi @bevacqua, I thought this was a neat little project! It reads a bit awkward though when you look at the profile for a woman (like myself) because all the pronouns are he/his. It would be nice if everything could read they/them/their. While not perfect, this would be more inclusive for a few different genders. I'm happy to submit a PR for this update if you prefer. :]

**Comment by bevacqua** [comment]
Yes! Please. This project is in dire need for better wording. I can add you as a collaborator if you want, too 👍

**Comment by melanierichards** [comment]
Awesome! Collaborator works.

**Comment by bevacqua** [comment]
Amazing. Sent invite.

**Comment by melanierichards** [comment]
Oh and I forgot to ask, any particular workflow you want to follow, or just work on a feature branch and put in a PR?

**Comment by bevacqua** [comment]
That works
