### ISSUE TITLE
Feature request: count user's published libraries under organisations too

### ISSUE THREAD

**Issue by revelt** [bevacqua/hubby#9]
Hi Nicolás,

Many people, including myself, publish libraries on organisations too, besides their personal accounts. Currently those libraries are not included and it's not fair.

Is it technically possible to include contributions to organisations too?

cheers
Roy

**Comment by bevacqua** [comment]
Feel free to submit a PR to that effect

**Comment by revelt** [comment]
Thank you, I'll try.
